# Generated by Django 2.2.6 on 2019-10-29 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('First_Name', models.CharField(max_length=200)),
                ('Middle_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('tutorial_published', models.DateTimeField(default=datetime.datetime(2019, 10, 29, 16, 29, 4, 94135), verbose_name='date published')),
            ],
        ),
    ]
