# Generated by Django 2.2.6 on 2019-10-29 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 16, 29, 24, 345722), verbose_name='date published'),
        ),
    ]
